version: '3.8'

services:
  
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    networks:
      - backend
    ports:
      - 27017:27017
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: noworry
      MONGO_INITDB_ROOT_PASSWORD: itsalocalapp
    command: mongod --auth

  server:
    build: 
      context: ./
      dockerfile: ./docker/Dev.Dockerfile
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/app
    environment:
      MONGODB_URI: "mongodb://noworry:itsalocalapp@mongo"
    ports:
      - $LV_SRV_PORT:$LV_SRV_PORT
    depends_on:
      - mongo
    networks:
      - backend
    command: npm run dev

networks:
  backend:

volumes:
  mongodb: