export default [
    'LV_SRV_PORT',
    'LV_PROXY_LEVEL',
    'XTREAM_CODES_BASE_URL',
    'XTREAM_CODES_USERNAME',
    'XTREAM_CODES_PASSWORD',
    'LV_URL',
    'LV_HOST',
    'LV_USER',
    'LV_PASS',
    'LV_MAX_SESSIONS',
    'LV_JWT_SECRET',
    'LV_JWT_EXPIRES_IN'
];